version: '3.8'

services:
  wordpress:
    container_name: ${PROJECT_NAME}_web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./wordpress_data:/var/www/html
    depends_on:
      - db
  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./database_data:/var/lib/mysql

